function openAuth(mode){document.getElementById('auth').classList.remove('hidden');const reg=mode==='register';document.getElementById('authTitle').textContent=reg?'Create account':'Welcome back';document.getElementById('authSub').textContent=reg?'Start using the prediction dashboard.':'Log in to continue.';document.getElementById('name').style.display=reg?'block':'none';document.getElementById('switchText').innerHTML=reg?'Already have an account? <a onclick="openAuth(\\'login\\')">Log in</a>':'Need an account? <a onclick="openAuth(\\'register\\')">Create one</a>'}
function closeAuth(){document.getElementById('auth').classList.add('hidden')}
function submitAuth(e){e.preventDefault();const email=document.getElementById('email').value;const name=document.getElementById('name').value||email.split('@')[0];localStorage.setItem('gmUser',JSON.stringify({name,email}));location.href='dashboard.html'}
function logout(){localStorage.removeItem('gmUser');location.href='index.html'}
function initDash(){const u=JSON.parse(localStorage.getItem('gmUser')||'null');if(!u){location.href='index.html';return}document.getElementById('userLabel').textContent=u.name;renderHistory()}
function setupImage(){const input=document.getElementById('imageInput');if(!input)return;input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=e=>{const p=document.getElementById('preview');p.src=e.target.result;p.classList.remove('hidden')};r.readAsDataURL(f)}}
function analyze(){const h=+document.getElementById('homeOdds').value,d=+document.getElementById('drawOdds').value,a=+document.getElementById('awayOdds').value;if(!(h>1&&d>1&&a>1)){alert('Please enter valid decimal odds.');return}const raw=[1/h,1/d,1/a],sum=raw.reduce((x,y)=>x+y,0),p=raw.map(x=>x/sum*100);const labels=['Home win','Draw','Away win'];let best=p.indexOf(Math.max(...p));const market=best===0?'Home win':best===1?'Draw':'Away win';const confidence=Math.round(p[best]);const rec=confidence>=50?market:(p[0]+p[1]>p[2]?'Home or Draw':'Away or Draw');const now=new Date().toLocaleString();let hist=JSON.parse(localStorage.getItem('gmHistory')||'[]');hist.unshift({time:now,pick:rec,confidence,probs:p.map(x=>x.toFixed(1))});hist=hist.slice(0,20);localStorage.setItem('gmHistory',JSON.stringify(hist));document.getElementById('result').innerHTML='<div class="prediction"><div class="pill">MODEL OUTPUT</div><div class="bigpick">'+rec+'</div><p>Highest estimated probability: <b>'+confidence+'%</b></p>'+labels.map((l,i)=>'<div class="prob"><div><span>'+l+'</span><b>'+p[i].toFixed(1)+'%</b></div><div class="bar"><i style="width:'+p[i]+'%"></i></div></div>').join('')+'<div class="pick">⚠ This is an odds-based estimate, not a guaranteed outcome.</div></div>';document.getElementById('count').textContent=hist.length;renderHistory()}
function renderHistory(){const h=JSON.parse(localStorage.getItem('gmHistory')||'[]');const el=document.getElementById('history');if(!el)return;document.getElementById('count').textContent=h.length;if(!h.length){el.innerHTML='<p class="muted">No predictions yet.</p>';return}el.innerHTML='<div class="row"><b>Time</b><b>Pick</b><b>Confidence</b><b>Status</b></div>'+h.map(x=>'<div class="row"><span>'+x.time+'</span><span class="tag">'+x.pick+'</span><span>'+x.confidence+'%</span><span>Pending</span></div>').join('')}
if(location.pathname.endsWith('dashboard.html')){initDash();setupImage()}
